name: Hello

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '*/15 * * * *'

jobs:
  Hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        uses: ./.github/actions/test
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
